# Generated by Django 4.1.3 on 2022-11-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_categories_updated_at_alter_products_image_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
