# Generated by Django 4.1.3 on 2022-11-08 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cart_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='api.products'),
        ),
        migrations.AlterField(
            model_name='user_cart_products',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
