# Generated by Django 4.1.3 on 2022-11-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_cart_products_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart_products',
            name='price',
        ),
    ]
