# Generated by Django 4.1.3 on 2022-11-10 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_cart_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart_products',
            name='product_id',
        ),
        migrations.AddField(
            model_name='user_cart_products',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.products'),
        ),
    ]
