# Generated by Django 4.1.3 on 2022-11-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_cart_products_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_cart_products',
            old_name='products',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='user_cart_products',
            name='product_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
