# Generated by Django 4.1.3 on 2022-11-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_user_cart_products_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart_products',
            name='price',
        ),
    ]
