# Generated by Django 4.1.3 on 2022-11-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_user_cart_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_cart_products',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='user_cart_products',
            old_name='user_id',
            new_name='user',
        ),
    ]
