# Generated by Django 4.1.3 on 2022-11-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_cart_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart_products',
            name='price',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
