# Generated by Django 4.1.3 on 2022-11-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_cart_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart_products',
            name='price',
        ),
    ]
