# Generated by Django 4.1.3 on 2022-11-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_user_cart_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category_id',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.categories'),
        ),
    ]
