# Generated by Django 4.1.3 on 2022-11-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_categories_active_remove_products_category_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Logs',
        ),
        migrations.DeleteModel(
            name='User_Logs',
        ),
    ]
