# Generated by Django 4.1.3 on 2022-11-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_admin_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_logs',
            name='product',
        ),
        migrations.AddField(
            model_name='admin_logs',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
