# Generated by Django 4.1.3 on 2022-11-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_admin_logs_product_admin_logs_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_logs',
            old_name='product_id',
            new_name='object_pk',
        ),
        migrations.AddField(
            model_name='admin_logs',
            name='object_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
